name: Bug Report
description: Create a bug report.
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Also tell us, how can we reproduce this bug?
      placeholder: |
        Steps to reproduce the behavior, please provide code snippets or a repository:

        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true
  - type: input
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Mac
        - Linux
        - Windows
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
