name: Feature Request
description: Request a new feature.
title: '[Feature]: '
labels: ['feature', 'triage']
body:
  - type: input
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what is the issue you're having and how your feature can solve it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: input
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: true
